[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_bot = "5QySMwEVWLGXj1zhGo2KQSgXUJRvEEnRGU911KZofFcr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"
