symbol = "BTCUSDT"
pair = "BTC/USDT" 

[timeframe]
interval = "2h" # Interval to calculate average price
tick = "30m" # Timeframe for a single bar

[exchange]
api = "binance" # Which api bot should use to collect data(Currently only binance supported)

[risk_management]
capital_per_trade = 0.1 # Percent of all capital for single position
max_positions = 5 # Max position bot would be operate in a single timeframe
max_drawdown = 3.5 # Max deviation from average price in percent, once reached all the trades would be stopped, could be treated as a guard for Mean Reversion strategy
stop_loss = 0.5 # Stop loss percentage, determine point to sell position if loss reach specified value
profit_level = 0.2 # Determine point when to close position

[timeframe.period_measurement]
measure_bars = 20 # How many bars bot should consider when calculating average price
mean_calculation_method="SimpleMA" # Simple MA, EMA, VWAP

[measurement_deviation]
enter_deviation = 0.20 # Determine on what deviation level bot should buy assets
