# see ./strategy.md for configuration guide
symbol = "BTCUSDT"
pair = "BTC/USDT"
trading_symbol = "USDT"

[timeframe]
interval = "2h"
tick = "30m"

[exchange]
api = "binance"

[risk_management]
capital_per_trade = 0.1
max_positions = 5
max_drawdown = 3.5
stop_loss = 0.5
profit_level = 0.2

[timeframe.period_measurement]
measure_bars = 20
mean_calculation_method = "SimpleMA"

[measurement_deviation]
enter_deviation = 0.15
